# Generated by Django 5.0.1 on 2024-01-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arvore', '0004_solicitacaodoacao_especie_efetivardoacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MudaArvore',
        ),
    ]
