# Generated by Django 5.0.1 on 2024-01-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvore', '0005_delete_mudaarvore'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodoacao',
            name='local_de_plantio',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
