# Generated by Django 5.0.1 on 2024-01-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvore', '0006_solicitacaodoacao_local_de_plantio'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivardoacao',
            name='data_efetivacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='efetivardoacao',
            name='data_plantio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaodoacao',
            name='data_solicitacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
