# Generated by Django 5.0.1 on 2024-01-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvore', '0008_efetivardoacao_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodoacao',
            name='observacoes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
