# Generated by Django 5.0.1 on 2024-02-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvore', '0013_remove_doacaoavulso_quantidade_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacaoavulso',
            name='especies_quantidades',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
