# Generated by Django 5.0.1 on 2024-02-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvore', '0014_doacaoavulso_especies_quantidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacaoavulso',
            name='especies_quantidades',
        ),
        migrations.AlterField(
            model_name='especiequantidade',
            name='especie',
            field=models.CharField(max_length=150),
        ),
    ]
