# Generated by Django 5.0.1 on 2024-02-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvore', '0015_remove_doacaoavulso_especies_quantidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaoavulso',
            name='data_adocao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doacaoavulso',
            name='data_plantio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
